[package]
name = "example-hello-world"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = { path = "../.." }
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
hyper = "0.14"
